In [1]:
import numpy as np 
import scipy 
import matplotlib.pyplot as plt

# Задание 2 

In [2]:
A= [ [19, 6,4],[8,22,4], [  4,4,19]   ]
b= [   9,5,3] 

In [3]:
x_np = np.linalg.solve(A, b)
print("%.4f "*len(x_np) % tuple(x_np) )

0.4450 0.0559 0.0524 


In [4]:
B= []
c= []

for i in range(len(b)):
    c.append(b[i]/A[i][i])
    B.append([])
    for j in range(len(b)):
        if(i==j):
            B[i].append(0)
        else:
            B[i].append(-A[i][j]/A[i][i])

In [5]:
def zeid(B,c,iterations,x_start  ):
    #возвращает массив - вектор решений 
    y=x_start.copy()
   
    for k in range(iterations):
        x_k = y.copy()      
        for i in range(len(c)):
            u=0
            for j in range(i):
                u=u+B[i][j]*y[j]  #использование новых значений x^{k+1}          
            for j in range(i+1, len(c)):
                u=u+B[i][j]*x_k[j]          
            y[i] = u+c[i]
        print("iteration:" ,k+1)
        print("%.3f "*len(y) % tuple(y) )
        k = 0
        for i in range(len(b)):
            if (np.abs(x_k[i]-y[i])<0.01):
                k+=1
                
        if (k==len(b) ):
            print("Condition to finish")
            break
        
    return y    
    

In [6]:
x = zeid(B, c, 10, [0,0,0])

iteration: 1
0.474 0.055 0.047 
iteration: 2
0.447 0.056 0.052 
iteration: 3
0.445 0.056 0.052 
Condition to finish


Трех итераций хватило (при оценке в разнице итераций)

Решение адекватно (сравнивалась с решением из библиотеки) /

# Задание 3

In [7]:
A= np.array([ [-5, -4, 6],[ -4,9,2], [  6,2,4]   ])
np.linalg.eigvals(A)

array([-9.10468636,  7.        , 10.10468636])

In [10]:
def GetMaxValue(A):
    max_value, c_i, c_j = 0, -1, -1
    for i in range(len(A)):
        for j in range(len(A) - i - 1):
            if abs(A[i][len(A) - j - 1]) > abs(max_value):
                max_value, c_i, c_j = A[i,len(A) - j - 1], i, len(A) - j - 1
    return max_value, c_i, c_j

def Yacobi(A, err=1e-3):
    eig_is_changed = False
    eigVectMatrix = np.array([[0.] * len(A)] * len(A))
    Aij_max, i, j = GetMaxValue(A)
    counter = 0
    while (abs(Aij_max)>err):
        counter += 1
        phi = np.arctan(2 * Aij_max/(A[i,i]-A[j,j])) / 2
        H = np.zeros_like(A, dtype=float) 
        for k in range(len(A)):
            H[k,k] = 1
        H[j,j] = H[i][i] = np.cos(phi)
        H[i,j] = -np.sin(phi)
        H[j,i] = np.sin(phi)
        A = np.dot(np.dot(H.T, A), H)
        if eig_is_changed:
            eigVectMatrix = np.dot(eigVectMatrix, H)
        else:
            eigVectMatrix = H
            eig_is_changed = True
        Aij_max, i, j = GetMaxValue(A)
    eigenvalues = np.diagonal(A) 
    return eigenvalues 

In [11]:
Yacobi(A, err=1e-3)

array([-9.10468636, 10.10468636,  7.        ])

Решение совпадает с решением из библиотеки Numpy

# Задание 4 

In [22]:
A = np.array([[5,5], [5,7]])

np.linalg.eigvals(A)

array([ 0.90098049, 11.09901951])

взяла прямо с семинара, алгоритм легкий, но руками сложновато) 

In [23]:
for i in range(10):
  if i% 5 == 0:
    print('\n На шаге {:}'.format(i))
    for i in range(len(A)):
        print("%.1f "*len(A[i]) % tuple(A[i]) )

  Q, R = np.linalg.qr(A)
  A = R@Q


 На шаге 0
5.0 5.0 
5.0 7.0 

 На шаге 5
11.1 -0.0 
-0.0 0.9 


In [24]:
eigenvalues = np.diagonal(A) 

print("%.4f "*len(eigenvalues) % tuple(eigenvalues) )

11.0990 0.9010 


# Задание 5

In [38]:
A = np.array([[0,0,1,0,1], [0,0,1,1,0], [0,0,1,0,1], [1,1,1,1,1], [1,0,1,0,1]])

A = A/np.sum(A, axis=0)
A

array([[0.  , 0.  , 0.2 , 0.  , 0.25],
       [0.  , 0.  , 0.2 , 0.5 , 0.  ],
       [0.  , 0.  , 0.2 , 0.  , 0.25],
       [0.5 , 1.  , 0.2 , 0.5 , 0.25],
       [0.5 , 0.  , 0.2 , 0.  , 0.25]])

In [39]:
x = np.ones(len(A))/len(A)

for i in range(21):
  x = np.dot(A, x)
  if i % 4 == 0:
    print("На шаге {:} вектор x = {:}".format(i, x))

На шаге 0 вектор x = [0.09 0.14 0.09 0.49 0.19]
На шаге 4 вектор x = [0.01702181 0.30522213 0.01702181 0.63045556 0.03027869]
На шаге 8 вектор x = [0.00293142 0.32882181 0.00293142 0.6601082  0.00520715]
На шаге 12 вектор x = [5.04463663e-04 3.32577341e-01 5.04463663e-04 6.65517650e-01
 8.96081646e-04]
На шаге 16 вектор x = [8.68119201e-05 3.33204511e-01 8.68119201e-05 6.66467661e-01
 1.54204488e-04]
На шаге 20 вектор x = [1.49392506e-05 3.33311244e-01 1.49392506e-05 6.66632341e-01
 2.65366725e-05]


In [40]:
beta = 0.85

x_weaked = (1-beta)*x + beta*np.ones(len(A))/len(A)

x_weaked

array([0.17000224, 0.21999669, 0.17000224, 0.26999485, 0.17000398])

In [41]:
np.sum(x_weaked)

0.9999999999999998

# Задание  6 

In [124]:
A = np.array([[0.5, 0.45, 0.65], [0.45,0.6,0.5], [0.65, 0.5, 0.6]])

L = np.linalg.inv(np.identity(len(b))-A)
L

array([[ 0.15319149, -0.85957447, -0.82553191],
       [-0.85957447,  0.3787234 , -0.92340426],
       [-0.82553191, -0.92340426,  0.00425532]])

Матрица продуктивная (раз L существует )

In [125]:
vals = Yacobi(A, err=1e-3)
np.max(vals)

1.6378513077371213

Это число Перрона-ФРобениуса 

Самая значимая вершина - третья 

# Задание 7 

In [61]:
A = np.array([[187,155,91],[114,198,120], [277,173,226]])
b=np.array([975, 1041, 1186])

Вектор конченого спроса: 

In [62]:
c = b - np.dot(A, np.ones(len(b)))

c

array([542., 609., 510.])

Матрица расходных коэффициентов: 

In [63]:
U = np.zeros_like(A, dtype=float)

for i in range(len(b)):
    U[i, :] = A[i,:]/b
    
U

array([[0.19179487, 0.14889529, 0.0767285 ],
       [0.11692308, 0.19020173, 0.10118044],
       [0.28410256, 0.16618636, 0.19055649]])

Леонтьевская матрица: 

In [64]:
L = np.linalg.inv(np.identity(len(b))-U)

L

array([[1.33428462, 0.27842945, 0.16128274],
       [0.25777748, 1.32117826, 0.18958244],
       [0.52123808, 0.36897489, 1.33094755]])

In [65]:
def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) > 0)

is_pos_def(L)

True

Модель продуктивна 

# Задание 8 

In [100]:
from scipy.interpolate import lagrange
from scipy import linalg

In [101]:
A=np.array([[-20, -19,-18], [48,43,39], [-22, -18, -15]])

A_1 = A+1
 

In [102]:
eigvals, eigvectors  = np.linalg.eig(A_1)
eigvals, eigvectors  

(array([9.        , 0.99999986, 1.00000014]),
 array([[-0.38107277,  0.26726126,  0.26726123],
        [ 0.87494307, -0.80178373, -0.80178372],
        [-0.29876105,  0.53452247,  0.53452249]]))

In [103]:
J = np.zeros_like(A, dtype=float)
J[np.diag_indices_from(J)] = eigvals
J[1,2] = 1
J

array([[9.        , 0.        , 0.        ],
       [0.        , 0.99999986, 1.        ],
       [0.        , 0.        , 1.00000014]])

In [104]:
np.dot(np.dot(eigvectors.T, J), eigvectors)

array([[ 1.90033262, -1.31014668, -1.31014657],
       [-1.53828166,  1.14285716,  1.14285708],
       [-1.53828157,  1.1428571 ,  1.14285703]])

# Задание 10 

In [120]:
A = np.array([[-2,0], [0,0]])

np.linalg.norm( np.dot(A, A), -2)

0.0

In [121]:

np.linalg.norm( np.dot(A@A, A), -2)

0.0

Взяла нормой -2  - самое маленькое собственное значение, должно сходиться